---
git:
  tagName: "v${version}"
  commitMessage: 'chore(release): v${version}'
  changelog: npx auto-changelog --breaking-pattern "BREAKING CHANGE:" --stdout --commit-limit false -u --template https://raw.githubusercontent.com/release-it/release-it/master/templates/changelog-compact.hbs

github:
  release: true
  assets: ["dist/*.unitypackage"]

npm: false

plugins:
  "@release-it/conventional-changelog":
    preset: angular
    infile: CHANGELOG.md
    ignoreRecommendedBump: true
    
hooks:
  after:bump: "node ./Scripts/update_package_version.js ${version}"
  before:github: "node ./Scripts/generate_unitypackage.js v${version}"
