//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIComponents.Roslyn.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIComponents.Roslyn.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIComponents use code generation and must be partial..
        /// </summary>
        internal static string UIC001_Description {
            get {
                return ResourceManager.GetString("UIC001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIComponent type &apos;{0}&apos; is not partial.
        /// </summary>
        internal static string UIC001_MessageFormat {
            get {
                return ResourceManager.GetString("UIC001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIComponent type is not partial.
        /// </summary>
        internal static string UIC001_Title {
            get {
                return ResourceManager.GetString("UIC001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods that begin with UIC_ are used internally by UIComponents&apos;s generated code and should not be used otherwise..
        /// </summary>
        internal static string UIC002_Description {
            get {
                return ResourceManager.GetString("UIC002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage of internal UIComponent method &apos;{0}&apos; is not recommended.
        /// </summary>
        internal static string UIC002_MessageFormat {
            get {
                return ResourceManager.GetString("UIC002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal UIComponent methods should not be used.
        /// </summary>
        internal static string UIC002_Title {
            get {
                return ResourceManager.GetString("UIC002_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stylesheet has already been declared in the UIComponent..
        /// </summary>
        internal static string UIC101_Description {
            get {
                return ResourceManager.GetString("UIC101_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identical stylesheet &apos;{0}&apos; in {1}.
        /// </summary>
        internal static string UIC101_MessageFormat {
            get {
                return ResourceManager.GetString("UIC101_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identical stylesheet in UIComponent.
        /// </summary>
        internal static string UIC101_Title {
            get {
                return ResourceManager.GetString("UIC101_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UxmlNameAttribute must be given a non-empty string..
        /// </summary>
        internal static string UIC102_Description {
            get {
                return ResourceManager.GetString("UIC102_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UxmlNameAttribute with empty string.
        /// </summary>
        internal static string UIC102_MessageFormat {
            get {
                return ResourceManager.GetString("UIC102_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UxmlNameAttribute with empty string.
        /// </summary>
        internal static string UIC102_Title {
            get {
                return ResourceManager.GetString("UIC102_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UxmlTraitAttribute&apos;s name must not be empty..
        /// </summary>
        internal static string UIC103_Description {
            get {
                return ResourceManager.GetString("UIC103_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UxmlTraitAttribute with empty name.
        /// </summary>
        internal static string UIC103_MessageFormat {
            get {
                return ResourceManager.GetString("UIC103_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UxmlTraitAttribute with empty name.
        /// </summary>
        internal static string UIC103_Title {
            get {
                return ResourceManager.GetString("UIC103_Title", resourceCulture);
            }
        }
    }
}
