//HintName: UIComponentAssetRegistry.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

[GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-beta.11")]
internal static class UIComponentAssetRegistry
{
    public struct AssetEntry
    {
        public string LayoutPath;
        public string[] StylesheetPaths;
    }

    private static readonly Dictionary<Type, AssetEntry> Entries = new Dictionary<Type, AssetEntry>
    {
        { typeof(global::ChildComponent), new AssetEntry { LayoutPath = "ChildComponent", StylesheetPaths = new[] { "Shared/Base", "ChildComponent.style" } } },
    };

    public static bool TryGetEntry(Type componentType, out AssetEntry entry)
    {
        return Entries.TryGetValue(componentType, out entry);
    }
}
