//HintName: BaseEffectComponent.Effects.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System;
using UnityEngine.UIElements;

public partial class BaseEffectComponent
{
    private static UIComponentEffectAttribute[] UIC_EffectAttributes;

    private static void UIC_InitializeEffectAttributes()
    {
        UIC_EffectAttributes = new [] {
            new TestEffectAttribute()
        };
        Array.Sort(UIC_EffectAttributes);
    }

    protected override void ApplyEffects()
    {
        if (UIC_EffectAttributes == null)
            UIC_InitializeEffectAttributes();

        foreach (var effect in UIC_EffectAttributes)
            effect.Apply(this);
    }
}
