//HintName: InventoryPanel.Layout.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using UIComponents;
using System.CodeDom.Compiler;
using UnityEngine.UIElements;
using System.Threading.Tasks;

public partial class InventoryPanel
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-beta.10")]
    protected override Task<VisualTreeAsset> UIC_StartLayoutLoad()
    {
        var path = AssetCatalog.ResolveLayoutPath(typeof(global::InventoryPanel), "UI/Components/InventoryPanel");
        return AssetResolver.LoadAsset<VisualTreeAsset>(path);
    }
}
