//HintName: ParentClass.FirstNestedComponent.Layout.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.Threading.Tasks;
using UnityEngine.UIElements;

public partial class ParentClass 
{
public partial class FirstNestedComponent
{
    protected override Task<VisualTreeAsset> StartLayoutLoad()
    {
        return AssetResolver.LoadAsset<VisualTreeAsset>("Components/FirstNestedComponent");
    }
}
}
