//HintName: ParentClass.SecondNestedComponent.Layout.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.Threading.Tasks;
using System.CodeDom.Compiler;
using UnityEngine.UIElements;

public partial class ParentClass 
{
private partial class SecondNestedComponent
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-alpha.2")]
    protected override Task<VisualTreeAsset> UIC_StartLayoutLoad()
    {
        return AssetResolver.LoadAsset<VisualTreeAsset>("Components/SecondNestedComponent");
    }
}
}
