//HintName: ParentClass.NestedComponent.Query.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.Collections.Generic;
using UnityEngine.UIElements;

namespace UILibrary.Components
{
public partial class ParentClass 
{
public partial class NestedComponent
{
    protected override void PopulateQueryFields()
    {
        field = this.Query<UnityEngine.UIElements.VisualElement>(null, (string) null).First();
        elements = this.Query<UnityEngine.UIElements.VisualElement>("uxml-name", "class-name").ToList();
    }
}
}
}
