//HintName: ListQueryComponent.Query.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.Collections.Generic;
using UnityEngine.UIElements;

public partial class ListQueryComponent
{
    protected override void PopulateQueryFields()
    {
        elements = this.Query<UnityEngine.UIElements.VisualElement>("uxml-name", "class-name").ToList();
    }
}
