//HintName: BasicQueryComponent.Query.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.Collections.Generic;
using System.CodeDom.Compiler;
using UnityEngine.UIElements;

public partial class BasicQueryComponent
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "0.26.0")]
    protected override void UIC_PopulateQueryFields()
    {
        element = this.Query<UnityEngine.UIElements.VisualElement>(null, (string) null).First();
        elementWithUxmlNameInConstructor = this.Query<UnityEngine.UIElements.VisualElement>("uxml-name", (string) null).First();
        elementWithUxmlNameAsNameArgument = this.Query<UnityEngine.UIElements.VisualElement>("second-uxml-name", (string) null).First();
        elementWithClassName = this.Query<UnityEngine.UIElements.VisualElement>(null, "class-name").First();
        elementWithNameAndClass = this.Query<UnityEngine.UIElements.VisualElement>("third-uxml-name", "second-class-name").First();
        elementProperty = this.Query<UnityEngine.UIElements.VisualElement>("fourth-uxml-name", "third-class-name").First();
    }
}
