//HintName: BaseQueryComponent.Query.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.Collections.Generic;
using System.CodeDom.Compiler;
using UnityEngine.UIElements;

public partial class BaseQueryComponent
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-alpha.4")]
    protected override void UIC_PopulateQueryFields()
    {
        // baseElement
        var UIC_baseElementList = new List<UnityEngine.UIElements.VisualElement>();
        this.Query<UnityEngine.UIElements.VisualElement>(null, (string) null).ToList(UIC_baseElementList);
        if (UIC_baseElementList.Count == 0)
            Logger.LogError("Query (baseElement): No instances of UnityEngine.UIElements.VisualElement found", this);
        if (UIC_baseElementList.Count > 0)
            baseElement = UIC_baseElementList[0];

        // anotherBaseElement
        var UIC_anotherBaseElementList = new List<UnityEngine.UIElements.VisualElement>();
        this.Query<UnityEngine.UIElements.VisualElement>("uxml-name", (string) null).ToList(UIC_anotherBaseElementList);
        if (UIC_anotherBaseElementList.Count == 0)
            Logger.LogError("Query (anotherBaseElement): No instances of UnityEngine.UIElements.VisualElement found", this);
        if (UIC_anotherBaseElementList.Count > 0)
            anotherBaseElement = UIC_anotherBaseElementList[0];
    }
}
