//HintName: ArrayQueryComponent.Query.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.Collections.Generic;
using System.CodeDom.Compiler;
using UnityEngine.UIElements;

public partial class ArrayQueryComponent
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "0.26.0")]
    protected override void UIC_PopulateQueryFields()
    {
        var elementsList = new List<UnityEngine.UIElements.VisualElement>();
        this.Query<UnityEngine.UIElements.VisualElement>("uxml-name", "class-name").ToList(elementsList);
        elements = new UnityEngine.UIElements.VisualElement[elementsList.Count];
        for (var i = 0; i < elementsList.Count; i++)
            elements[i] = elementsList[i];
    }
}
