//HintName: InvalidUsageQueryComponent.Query.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.Collections.Generic;
using System.CodeDom.Compiler;
using UnityEngine.UIElements;

public partial class InvalidUsageQueryComponent
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "0.26.0")]
    protected override void UIC_PopulateQueryFields()
    {
        element = this.Query<UnityEngine.UIElements.VisualElement>("valid-usage", (string) null).First();
    }
}
