//HintName: MultipleQueryComponent.Query.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.Collections.Generic;
using System.CodeDom.Compiler;
using UnityEngine.UIElements;

public partial class MultipleQueryComponent
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "0.26.0")]
    protected override void UIC_PopulateQueryFields()
    {
        var UIC_firstElementList = new List<UnityEngine.UIElements.VisualElement>();
        this.Query<UnityEngine.UIElements.VisualElement>(null, (string) null).ToList(UIC_firstElementList);
        this.Query<UnityEngine.UIElements.VisualElement>(null, "test").ToList(UIC_firstElementList);
        if (UIC_firstElementList.Count > 0)
             firstElement = UIC_firstElementList[0];
        var UIC_manyElementsArrayList = new List<UnityEngine.UIElements.VisualElement>();
        this.Query<UnityEngine.UIElements.VisualElement>("uxml-name", "class").ToList(UIC_manyElementsArrayList);
        this.Query<UnityEngine.UIElements.VisualElement>(null, "class-name").ToList(UIC_manyElementsArrayList);
        manyElementsArray = new UnityEngine.UIElements.VisualElement[UIC_manyElementsArrayList.Count];
        for (var i = 0; i < UIC_manyElementsArrayList.Count; i++)
            manyElementsArray[i] = UIC_manyElementsArrayList[i];
        var UIC_manyElementsListList = new List<UnityEngine.UIElements.VisualElement>();
        this.Query<UnityEngine.UIElements.VisualElement>("name", "class").ToList(UIC_manyElementsListList);
        this.Query<UnityEngine.UIElements.VisualElement>("other-name", "other-class").ToList(UIC_manyElementsListList);
        this.Query<UnityEngine.UIElements.VisualElement>("third-name", "third-class").ToList(UIC_manyElementsListList);
        manyElementsList = UIC_manyElementsListList;
    }
}
