//HintName: Parent.PTwo.PThree.PFour.FirstNestedComponent.Query.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.Collections.Generic;
using UnityEngine.UIElements;

public partial class Parent 
{
private partial class PTwo 
{
protected partial class PThree 
{
internal partial class PFour 
{
public partial class FirstNestedComponent
{
    protected override void PopulateQueryFields()
    {
        field = this.Query<UnityEngine.UIElements.VisualElement>(null, (string) null).First();
        elements = this.Query<UnityEngine.UIElements.VisualElement>("uxml-name", "class-name").ToList();
    }
}
}
}
}
}
