//HintName: MyComponent.Query.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using UIComponents;
using MyLibrary.Core.Elements;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using UnityEngine.UIElements;

namespace MyLibrary.GUI
{
public partial class MyComponent
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-beta.0")]
    protected override void UIC_PopulateQueryFields()
    {
        // element
        var UIC_elementList = new List<MyElement>();
        this.Query<MyElement>(null, (string) null).ToList(UIC_elementList);
        if (UIC_elementList.Count == 0)
            Logger.LogError("Query (element): No instances of MyElement found", this);
        if (UIC_elementList.Count > 0)
            element = UIC_elementList[0];
    }
}
}
