//HintName: Parent.PTwo.PThree.PFour.SecondNestedComponent.Query.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.Collections.Generic;
using System.CodeDom.Compiler;
using UnityEngine.UIElements;

public partial class Parent 
{
private partial class PTwo 
{
protected partial class PThree 
{
internal partial class PFour 
{
private partial class SecondNestedComponent
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-alpha.1")]
    protected override void UIC_PopulateQueryFields()
    {
        // component
        var UIC_componentList = new List<Parent.PTwo.PThree.PFour.FirstNestedComponent>();
        this.Query<Parent.PTwo.PThree.PFour.FirstNestedComponent>(null, (string) null).ToList(UIC_componentList);
        if (UIC_componentList.Count > 0)
             component = UIC_componentList[0];
    }
}
}
}
}
}
