//HintName: ParentClass.NestedComponent.Query.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.Collections.Generic;
using System.CodeDom.Compiler;
using UnityEngine.UIElements;

namespace UILibrary.Components
{
public partial class ParentClass 
{
public partial class NestedComponent
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-alpha.1")]
    protected override void UIC_PopulateQueryFields()
    {
        var UIC_fieldList = new List<UnityEngine.UIElements.VisualElement>();
        this.Query<UnityEngine.UIElements.VisualElement>(null, (string) null).ToList(UIC_fieldList);
        if (UIC_fieldList.Count > 0)
             field = UIC_fieldList[0];
        var UIC_elementsList = new List<UnityEngine.UIElements.VisualElement>();
        this.Query<UnityEngine.UIElements.VisualElement>("uxml-name", "class-name").ToList(UIC_elementsList);
        elements = UIC_elementsList;
    }
}
}
}
