//HintName: Components.ComponentWithOnCallback.RegistersCallbackAttribute.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.CodeDom.Compiler;
using UnityEngine.UIElements;

namespace MyLibrary.Tests.Runtime.Interfaces
{
public partial class Components 
{
private partial class ComponentWithOnCallback
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-alpha.1")]
    protected override void UIC_RegisterCallbacks()
    {
        RegisterCallback<OnCallbackEvent>(OnCallback);
    }

    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-alpha.1")]
    protected override void UIC_DeregisterCallbacks()
    {
        DeregisterCallback<OnCallbackEvent>(OnCallback);
    }
}
}
}
