//HintName: MyComponent.RegistersCallbackAttribute.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.CodeDom.Compiler;
using UnityEngine.UIElements;

namespace MyLibrary.Components
{
public partial class MyComponent
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-alpha.2")]
    protected override void UIC_RegisterCallbacks()
    {
        RegisterCallback<Events.MyEvent>(OnEvent);
    }

    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-alpha.2")]
    protected override void UIC_UnregisterCallbacks()
    {
        UnregisterCallback<Events.MyEvent>(OnEvent);
    }
}
}
