//HintName: Tests.OnEventComponent.RegistersCallbackAttribute.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.CodeDom.Compiler;
using UnityEngine.UIElements;

namespace UIComponents.Tests.Editor.Interfaces
{
public partial class Tests 
{
private partial class OnEventComponent
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-alpha.4")]
    protected override void UIC_RegisterCallbacks()
    {
        RegisterCallback<UnityEngine.UIElements.Event>(OnEvent);
    }

    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-alpha.4")]
    protected override void UIC_UnregisterCallbacks()
    {
        UnregisterCallback<UnityEngine.UIElements.Event>(OnEvent);
    }
}
}
}
