//HintName: ConcreteStylesheetComponent.Stylesheet.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using System.Threading.Tasks;
using UnityEngine.UIElements;

public partial class ConcreteStylesheetComponent
{
    private async Task<StyleSheetLoadTuple> GetSingleStyleSheet(string assetPath)
    {
        var styleSheet = await AssetResolver.LoadAsset<StyleSheet>(assetPath);
        return new StyleSheetLoadTuple(assetPath, styleSheet);
    }

    protected override Task<StyleSheetLoadTuple>[] StartStyleSheetLoad()
    {
        var assetPaths = new string[] { "Components/BaseStylesheet", "Components/StylesheetOne", "Components/StylesheetTwo" };
        var styleSheetLoadTasks = new Task<StyleSheetLoadTuple>[assetPaths.Length];

        for (var i = 0; i < assetPaths.Length; i++)
            styleSheetLoadTasks[i] = GetSingleStyleSheet(assetPaths[i]);

        return styleSheetLoadTasks;
    }
}
