//HintName: MyEnumComponentWithUsing.Uxml.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using UnityEngine.UIElements;

public partial class MyEnumComponentWithUsing
{
    public new partial class UxmlFactory : UxmlFactory<MyEnumComponentWithUsing, UxmlTraits> {}

    public new partial class UxmlTraits : VisualElement.UxmlTraits
    {
        UxmlEnumAttributeDescription<MyEnum> m_FieldTrait = new UxmlEnumAttributeDescription<MyEnum> { name = "fieldtrait" };
        UxmlEnumAttributeDescription<MyEnum> m_PropertyTrait = new UxmlEnumAttributeDescription<MyEnum> { name = "propertytrait" };

        public override void Init(VisualElement ve, IUxmlAttributes bag, CreationContext cc)
        {
            base.Init(ve, bag, cc);
            ((MyEnumComponentWithUsing)ve).FieldTrait = m_FieldTrait.GetValueFromBag(bag, cc);
            ((MyEnumComponentWithUsing)ve).PropertyTrait = m_PropertyTrait.GetValueFromBag(bag, cc);
        }
    }
}
