//HintName: ThirdTraitClass.UxmlTraits.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using UnityEngine.UIElements;

public partial class ThirdTraitClass
{
    public new partial class UxmlFactory : UxmlFactory<ThirdTraitClass, UxmlTraits> {}

    public new partial class UxmlTraits : VisualElement.UxmlTraits
    {
        UxmlStringAttributeDescription m_Name = new UxmlStringAttributeDescription { name = "name" };

        public override void Init(VisualElement ve, IUxmlAttributes bag, CreationContext cc)
        {
            base.Init(ve, bag, cc);
            ((ThirdTraitClass)ve).Name = m_Name.GetValueFromBag(bag, cc);
        }
    }
}
