//HintName: ComponentWithDefaultValueTraits.Uxml.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using UIComponents;
using System.CodeDom.Compiler;
using UnityEngine.UIElements;

public partial class ComponentWithDefaultValueTraits
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-beta.9")]
    public new partial class UxmlFactory : UxmlFactory<ComponentWithDefaultValueTraits, UxmlTraits> {}

    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-beta.9")]
    public new partial class UxmlTraits : VisualElement.UxmlTraits
    {
        UxmlStringAttributeDescription m_Description = new UxmlStringAttributeDescription { name = "description" };
        UxmlIntAttributeDescription m_Lives = new UxmlIntAttributeDescription { name = "lives" };
        UxmlEnumAttributeDescription<Some.Place.Where.Enum.Is.TheEnum> m_MyValue = new UxmlEnumAttributeDescription<Some.Place.Where.Enum.Is.TheEnum> { name = "custom-value" };

        [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-beta.9")]
        public override void Init(VisualElement ve, IUxmlAttributes bag, CreationContext cc)
        {
            base.Init(ve, bag, cc);

            var element = (ComponentWithDefaultValueTraits) ve;

            m_Description.defaultValue = "Description not set.";
            m_Lives.defaultValue = 3;
            m_MyValue.defaultValue = Some.Place.Where.Enum.Is.TheEnum.VALUE_B;
            element.Description = m_Description.GetValueFromBag(bag, cc);
            element.Lives = m_Lives.GetValueFromBag(bag, cc);
            element.MyValue = m_MyValue.GetValueFromBag(bag, cc);
        }
    }
}
