//HintName: DoubleComponentWithUsing.UxmlTraits.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using UnityEngine.UIElements;

public partial class DoubleComponentWithUsing
{
    public new partial class UxmlFactory : UxmlFactory<DoubleComponentWithUsing, UxmlTraits> {}

    public new partial class UxmlTraits : VisualElement.UxmlTraits
    {
        UxmlDoubleAttributeDescription m_FieldTrait = new UxmlDoubleAttributeDescription { name = "fieldtrait" };
        UxmlDoubleAttributeDescription m_PropertyTrait = new UxmlDoubleAttributeDescription { name = "propertytrait" };

        public override void Init(VisualElement ve, IUxmlAttributes bag, CreationContext cc)
        {
            base.Init(ve, bag, cc);
            ((DoubleComponentWithUsing)ve).FieldTrait = m_FieldTrait.GetValueFromBag(bag, cc);
            ((DoubleComponentWithUsing)ve).PropertyTrait = m_PropertyTrait.GetValueFromBag(bag, cc);
        }
    }
}
