//HintName: LongTraitNameComponent.Uxml.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using UIComponents;
using System.CodeDom.Compiler;
using UnityEngine.UIElements;

public partial class LongTraitNameComponent
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-beta.0")]
    public new partial class UxmlFactory : UxmlFactory<LongTraitNameComponent, UxmlTraits> {}

    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-beta.0")]
    public new partial class UxmlTraits : VisualElement.UxmlTraits
    {
        UxmlIntAttributeDescription m__member = new UxmlIntAttributeDescription { name = "member" };
        UxmlIntAttributeDescription m_memberTwo_ = new UxmlIntAttributeDescription { name = "member-two" };
        UxmlIntAttributeDescription m__member_three_ = new UxmlIntAttributeDescription { name = "member-three" };

        [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-beta.0")]
        public override void Init(VisualElement ve, IUxmlAttributes bag, CreationContext cc)
        {
            base.Init(ve, bag, cc);

            var element = (LongTraitNameComponent) ve;

            element._member = m__member.GetValueFromBag(bag, cc);
            element.memberTwo_ = m_memberTwo_.GetValueFromBag(bag, cc);
            element._member_three_ = m__member_three_.GetValueFromBag(bag, cc);
        }
    }
}
