//HintName: CustomNamespaceComponent.UxmlTraits.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

namespace Custom.Components
{
using UnityEngine.UIElements;

public partial class CustomNamespaceComponent
{
    public new partial class UxmlFactory : UxmlFactory<CustomNamespaceComponent, UxmlTraits> {}

    public new partial class UxmlTraits : VisualElement.UxmlTraits
    {
        UxmlEnumAttributeDescription<Custom.Components.CustomNamespaceComponent.OwnEnum> m_FieldTrait = new UxmlEnumAttributeDescription<Custom.Components.CustomNamespaceComponent.OwnEnum> { name = "fieldtrait" };
        UxmlEnumAttributeDescription<Custom.Components.CustomNamespaceComponent.OwnEnum> m_PropertyTrait = new UxmlEnumAttributeDescription<Custom.Components.CustomNamespaceComponent.OwnEnum> { name = "propertytrait" };

        public override void Init(VisualElement ve, IUxmlAttributes bag, CreationContext cc)
        {
            base.Init(ve, bag, cc);
            ((CustomNamespaceComponent)ve).FieldTrait = m_FieldTrait.GetValueFromBag(bag, cc);
            ((CustomNamespaceComponent)ve).PropertyTrait = m_PropertyTrait.GetValueFromBag(bag, cc);
        }
    }
}
}
