//HintName: MyUxmlNameAttributeComponent.Uxml.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using UnityEngine.UIElements;

public partial class MyUxmlNameAttributeComponent
{
    public new partial class UxmlFactory : UxmlFactory<MyUxmlNameAttributeComponent>
    {
        public override string uxmlName
        {
            get { return "MyUxmlNameAttribute"; }
        }

        public override string uxmlQualifiedName
        {
            get { return uxmlNamespace + "." + uxmlName; }
        }
    }
}
