//HintName: MyUxmlNameAttributeComponent.Uxml.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using UIComponents;
using System.CodeDom.Compiler;
using UnityEngine.UIElements;

public partial class MyUxmlNameAttributeComponent
{
    [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-beta.7")]
    public new partial class UxmlFactory : UxmlFactory<MyUxmlNameAttributeComponent>
    {
        [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-beta.7")]
        public override string uxmlName
        {
            get { return "MyUxmlNameAttribute"; }
        }

        [GeneratedCode("UIComponents.Roslyn.Generation", "1.0.0-beta.7")]
        public override string uxmlQualifiedName
        {
            get { return uxmlNamespace + "." + uxmlName; }
        }
    }
}
