//HintName: ColorComponentWithUsing.UxmlTraits.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using UnityEngine.UIElements;

public partial class ColorComponentWithUsing
{
    public new partial class UxmlFactory : UxmlFactory<ColorComponentWithUsing, UxmlTraits> {}

    public new partial class UxmlTraits : VisualElement.UxmlTraits
    {
        UxmlColorAttributeDescription m_FieldTrait = new UxmlColorAttributeDescription { name = "fieldtrait" };
        UxmlColorAttributeDescription m_PropertyTrait = new UxmlColorAttributeDescription { name = "propertytrait" };

        public override void Init(VisualElement ve, IUxmlAttributes bag, CreationContext cc)
        {
            base.Init(ve, bag, cc);
            ((ColorComponentWithUsing)ve).FieldTrait = m_FieldTrait.GetValueFromBag(bag, cc);
            ((ColorComponentWithUsing)ve).PropertyTrait = m_PropertyTrait.GetValueFromBag(bag, cc);
        }
    }
}
