//HintName: MyComponent.Uxml.g.cs
// <auto-generated>
// This file has been generated automatically by UIComponents.Roslyn.
// Do not attempt to modify it. Any changes will be overridden during compilation.
// </auto-generated>

using UnityEngine.UIElements;

public partial class MyComponent
{
    public new partial class UxmlFactory : UxmlFactory<MyComponent, UxmlTraits> {}

    public new partial class UxmlTraits : VisualElement.UxmlTraits
    {
        UxmlDoubleAttributeDescription m_Trait = new UxmlDoubleAttributeDescription { name = "double-value" };

        public override void Init(VisualElement ve, IUxmlAttributes bag, CreationContext cc)
        {
            base.Init(ve, bag, cc);
            ((MyComponent)ve).Trait = m_Trait.GetValueFromBag(bag, cc);
        }
    }
}
